# -*- coding:utf-8; -*-

#+title:21 Frames and Graphical Displays

* 21.14 Menu Bars

  You can toggle the use of menu bars with M-x menu-bar-mode. With no argument, this command toggles Menu Bar mode, a global minor mode. With an argument, the command turns Menu Bar mode on if the argument is positive, off if the argument is not positive. To control the use of menu bars at startup, customize the variable menu-bar-mode.

  可以使用 M-x menu-bar-mode 切换菜单栏的使用。没有参数，该命令将切换菜单栏，这是一个全局辅助模式。有参数的话，如果参数为正显示菜单栏，否则关闭。定制变量 menu-bar-mode 可以在启动的时候控制菜单栏的使用。

  Expert users often turn off the menu bar, especially on text terminals, where this makes one additional line available for text. If the menu bar is off, you can still pop up a menu of its contents with C-Mouse-3 on a display which supports pop-up menus. See Menu Mouse Clicks.

  专家用户经常关闭菜单栏，特别是在文本终端，这将会为文本产生一个额外可用的行。如果关闭菜单栏，在支持弹出菜单的显示中仍然可以使用 C-Mouse-3 弹出菜单项。

  See Menu Bar, for information on how to invoke commands with the menu bar. See X Resources, for how to customize the menu bar menus’ visual appearance.
